name:                shizen
version:             0.1.0.0
github:              "sergiodguezc/shizen"
license:             BSD3
author:              "Sergio Domínguez"
maintainer:          "sergdoma@ucm.es"
copyright:           "2022 Sergio Domínguez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sergiodguezc/shizen#readme>

dependencies:
- base >= 4.7 && < 5
- accelerate ==1.3.0.0
- llvm-hs ==9.0.1
- llvm-hs-pure ==9.0.0
- accelerate-llvm-native ==1.3.0.0
- accelerate-llvm-ptx ==1.3.0.0
- mwc-random-accelerate ==0.2.0.0
- mtl
- template-haskell
- linear-accelerate ==0.7.0.0
- containers-accelerate ==0.1.0.0

library:
  source-dirs: 
    - src 
    - lib

executables:
  shizen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -Wall
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-n2M 
    - -with-rtsopts=-A64M
    dependencies:
    - shizen

tests:
  shizen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shizen
